~ | Added sorting on utils/KiwiLeaderboard

diff --git a/utils/KiwiLeaderBoard b/utils/KiwiLeaderBoard
--- a/utils/KiwiLeaderBoard
+++ b/utils/KiwiLeaderBoard
@@ -1,64 +1,82 @@
 #!/bin/bash
 
 if [ -z "$CLIENT_ID" ]; then
-	echo "error: CLIENT_ID undefined"
-	exit 1
+    echo "error: CLIENT_ID undefined"
+    exit 1
 fi
 if [ -z "$CLIENT_SECRET" ]; then
-	echo "error: CLIENT_SECRET undefined"
-	exit 1
+    echo "error: CLIENT_SECRET undefined"
+    exit 1
 fi
 
 CAMPUS_ID=62
 START_DATE="2024-08-01T00:00:00.000Z"
 END_DATE="2024-09-01T00:00:00.000Z"
 BLACKLIST=("bbutcher" "42lhpirate")
+SORT_BY="level"
+
+for i in "$@"; do
+  case $i in
+    --sort=*)
+      SORT_BY="${i#*=}"
+      shift
+      ;;
+    *)
+      ;;
+  esac
+done
 
 ACCESS_TOKEN=$(curl -s -X POST --data "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" https://api.intra.42.fr/oauth/token | jq -r '.access_token')
 
 DATA_1=$(curl -s -G -H "Authorization: Bearer $ACCESS_TOKEN" \
     --data-urlencode "filter[active]=true" \
     --data-urlencode "page[size]=100" \
-	--data-urlencode "filter[campus_id]=$CAMPUS_ID" \
+    --data-urlencode "filter[campus_id]=$CAMPUS_ID" \
     --data-urlencode "range[created_at]=$START_DATE,$END_DATE" \
     "https://api.intra.42.fr/v2/cursus_users")
 
 DATA_2=$(curl -s -G -H "Authorization: Bearer $ACCESS_TOKEN" \
     --data-urlencode "filter[active]=true" \
     --data-urlencode "page[size]=100" \
-	--data-urlencode "page[number]=2" \
-	--data-urlencode "filter[campus_id]=$CAMPUS_ID" \
+    --data-urlencode "page[number]=2" \
+    --data-urlencode "filter[campus_id]=$CAMPUS_ID" \
     --data-urlencode "range[created_at]=$START_DATE,$END_DATE" \
     "https://api.intra.42.fr/v2/cursus_users")
 
-DATA=$(echo "$DATA_1 $DATA_2" | jq -s 'add')
+COMBINED_DATA=$(echo "$DATA_1 $DATA_2" | jq -s 'add')
 
-declare -a students_info
-
-logins=$(echo "$DATA" | jq -r '.[] | .user.login')
-correction_points=$(echo "$DATA" | jq -r '.[] | .user.correction_point')
-levels=$(echo "$DATA" | jq -r '.[] | .level')
-
-index=0
-while IFS= read -r login && IFS= read -r correction_point <&3 && IFS= read -r level <&4; do
-
+students_info=()
+while IFS=$'\t' read -r login correction_point level; do
     if [[ " ${BLACKLIST[@]} " =~ " $login " ]]; then
         continue
     fi
-
-    [[ "$level" == "null" || -z "$level" ]] && level=0
+    
+    level=$(printf "%.2f" "$level")
     user_url="https://profile.intra.42.fr/users/$login"
     students_info+=("$level $login $correction_point $user_url")
-    index=$((index + 1))
-done < <(printf "%s\n" "$logins") 3< <(printf "%s\n" "$correction_points") 4< <(printf "%s\n" "$levels")
+done < <(echo "$COMBINED_DATA" | jq -r '.[] | [.user.login, (.user.correction_point // 0), (.level // 0)] | @tsv')
 
-sorted_info=$(printf "%s\n" "${students_info[@]}" | sort -nr)
+case $SORT_BY in
+  level)
+    sorted_info=$(printf "%s\n" "${students_info[@]}" | sort -nr -k1)
+    ;;
+  correction_points)
+    sorted_info=$(printf "%s\n" "${students_info[@]}" | sort -nr -k3)
+    ;;
+  login)
+    sorted_info=$(printf "%s\n" "${students_info[@]}" | sort -k2)
+    ;;
+  *)
+    echo "Invalid sort option. Please use --sort=level, --sort=correction_points, or --sort=login."
+    exit 1
+    ;;
+esac
 
-printf "\033[1m┌──────────────────────────────────┐\033[0m\n"
-printf "\033[1m│       🥝 KIWI LEADERBOARD 🥝     │\033[0m\n"
-printf "\033[1m├───────┬─────────────┬───────┬────┤\033[0m\n"
-printf "\033[1m│ Index │    Login    │ Level │ EP │\033[0m\n"
-printf "\033[1m├───────┼─────────────┼───────┼────┤\033[0m\n"
+printf "\033[1m┌────────────────────────────────┐\033[0m\n"
+printf "\033[1m│    🥝 KIWI LEADERBOARD 🥝      │\033[0m\n"
+printf "\033[1m├───────┬───────────┬───────┬────┤\033[0m\n"
+printf "\033[1m│ Index │   Login   │ Level │ EP │\033[0m\n"
+printf "\033[1m├───────┼───────────┼───────┼────┤\033[0m\n"
 
 index=1
 while IFS= read -r line; do
@@ -79,8 +97,9 @@ while IFS= read -r line; do
         icon="  "
     fi
 
-    printf "│ %-5s │ \033[1m\e]8;;$user_url\a%-8s %-1s\e]8;;\a\033[0m │ %-5s │ %-2s │\n" "$index" "$login" "$icon" "$level" "$correction_point"
+    printf "│ %-5s │ \033[1m\e]8;;$user_url\a%-8s\e]8;;\a\033[0m │ %-5s │ %-2s │ %s\n" "$index" "$login" "$level" "$correction_point" "$icon"
     index=$((index + 1))
 done <<< "$sorted_info"
 
-printf "\033[1m└───────┴─────────────┴───────┴────┘\033[0m\n"
+printf "\033[1m└───────┴──────────┴───────┴────┘\033[0m\n"
+
